In [1]:
import numpy as np
import pandas as pd
import pygad

In [2]:
df = pd.read_csv('13.txt', delimiter=' ', engine='python')
df

      13000   12
993     1.0  275
285     0.7  168
1230    0.8  245
1139    1.1  225
736     0.5  339
524     0.7  220
229     0.5  153
372     0.4  191
466     1.2  179
543     0.7  184
984     1.0  191
728     1.1  219
1296    1.2  353
529     1.2  297
898     1.0  305
390     0.6  119
775     1.0  290
795     0.9  337
1058    0.5  336
176     0.7  342
927     0.9  249
482     0.6  226
714     0.7  196
801     0.6  234
1044    1.1  194
1550    0.9  378
950     0.9  364
447     0.8  263
707     1.0  199
1656    0.7  187

In [3]:
wv = df.columns.tolist()
W = int(wv[0]) 
V = int(wv[1]) 
df.columns = ['v', 'c']
df['w'] = df.index
data = df[['w','v','c']].values.tolist()

In [4]:
#Функция, вычисляющая ценность решения
def fitness_func(solution, solution_idx):
    w, v, c = 0, 0, 0
    for (array, item) in zip(solution, data):
        if array > 0:
            w += item[0]
            v += item[1]
            c += item[2]
    if w > W or v > V:
        c = 0
    return c

In [5]:
#Создаем экземпляр класса pygad.GA 
ga_instance = pygad.GA(num_generations=200, 
                       num_parents_mating=2, 
                       fitness_func=fitness_func, 
                       sol_per_pop=10, 
                       num_genes=len(data),
                       init_range_low=-1, 
                       init_range_high=1 
                       )

In [6]:
#Запускаем генетический алгоритм
ga_instance.run()
solution, solution_fitness, _ = ga_instance.best_solution()

In [7]:
result = []
for i in range(0, len(data)):
    if solution[i] > 0:
        result.append(data[i])
result_data = pd.DataFrame.from_records(result, columns=['w','v','c'])

In [8]:
print(solution_fitness)
print(result_data)
w, v, c = 0, 0, 0
for i in range(0, len(result_data)):
        w += result_data.at[i,'w']
        v += result_data.at[i,'v']
        c += result_data.at[i,'c']
print("Вес:", w)
print("Объем:", round(v,1))
print("Ценность:", c)

4200.0
         w    v      c
0    993.0  1.0  275.0
1   1230.0  0.8  245.0
2   1139.0  1.1  225.0
3    736.0  0.5  339.0
4    372.0  0.4  191.0
5    543.0  0.7  184.0
6    898.0  1.0  305.0
7    795.0  0.9  337.0
8   1058.0  0.5  336.0
9    176.0  0.7  342.0
10   927.0  0.9  249.0
11   714.0  0.7  196.0
12   801.0  0.6  234.0
13  1550.0  0.9  378.0
14   950.0  0.9  364.0
Вес: 12882.0
Объем: 11.6
Ценность: 4200.0

In [9]:
file=open('GA_4_1.txt','w', encoding='utf-8')
file.write(result_data.to_string())
file.write("\nВес: " + str(w))
file.write("\nОбъем: " + str(round(v,1)))
file.write("\nЦенность: " + str(c))
file.close()